### ISSUE TITLE
Note to Julian: Hold, and select text in text editor?

### ISSUE THREAD

**Issue by PLyczkowski** [carter2422/blender-presets#5]
I have a sticky key build here where selecting text in the editor stops after half a second - maybe it's connected to the hold key functionality?

**Comment by PLyczkowski** [comment]
Same with scrolling.

**Comment by julianeisel** [comment]
Good to see somebody still opening my testbuilds and reporting issues :) Thanks! In this case I'm already aware of it so I actually fixed it shortly after uploading the builds.
I can create new testbuilds if needed? Although I still recommend you to start building blender on your own ;)

**Comment by PLyczkowski** [comment]
Yeah, got to get around to that. I already built godot, time for Blender.
